import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import type Database from "better-sqlite3";
import path from "path";
import fs from "fs";
import * as schema from "./schema";
import { getDataDir, getMigrationsDir } from "@/lib/paths";

// Database file path: writable data directory (injected by the main process as APP_DATA_DIR=userData/data when packaged with Electron)
const DB_DIR = getDataDir();
const DB_PATH = path.join(DB_DIR, "sqlite.db");
// Migration files directory (generated by drizzle-kit, committed to the repo; points to resources/drizzle when packaged)
const MIGRATIONS_DIR = getMigrationsDir();

// 数据库初始化/迁移的失败状态：给 /api/health 与错误信息用。
// 背景（issue #12）：此前任何 init 失败（如打包进错 ABI 的 better_sqlite3.node）发生在模块加载期，
// Next 只回一个不带任何信息的 "Internal Server Error"，用户和维护者都无从下手。
// 现在把失败捕获下来：路由拿到的是带真实原因的异常（JSON 里可见），/api/health 可直接截图定位。
export let dbInitError: string | null = null;
export let dbMigrationError: string | null = null;

let sqlite: Database.Database | null = null;
let realDb: ReturnType<typeof drizzle<typeof schema>> | null = null;

try {
  // Ensure the data directory exists
  if (!fs.existsSync(DB_DIR)) {
    fs.mkdirSync(DB_DIR, { recursive: true });
  }

  // Create the better-sqlite3 connection instance.
  // 用 require 而非顶层 import：原生模块加载失败（ABI 不匹配/文件缺失）必须落进本 try 块，
  // 顶层 import 的失败发生在本模块求值之前，捕获不到。
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const BetterSqlite3 = require("better-sqlite3") as typeof Database;
  sqlite = new BetterSqlite3(DB_PATH);

  // Enable WAL mode for better concurrent read/write performance.
  // Skip during the next build phase: journal_mode=WAL rewrites the DB file header and requires
  // a brief exclusive lock; concurrent workers importing this module during the build race for
  // that lock and trigger "database is locked".
  // WAL is a persistent property of the DB file — setting it once at runtime (next start / Electron) is enough.
  if (process.env.NEXT_PHASE !== "phase-production-build") {
    sqlite.pragma("journal_mode = WAL");
  }
  // Enable foreign-key constraints (a per-connection pragma — does not write to the DB file or contend on locks, safe during build)
  sqlite.pragma("foreign_keys = ON");
  // Wait up to 5s on a locked database instead of failing instantly with SQLITE_BUSY —
  // a second process (CLI/MCP alongside the web server) touching the DB would otherwise error immediately.
  // Per-connection pragma, safe during build (same as foreign_keys).
  sqlite.pragma("busy_timeout = 5000");

  // Create the Drizzle ORM instance with the schema bound for relational queries
  realDb = drizzle(sqlite, { schema });
} catch (err) {
  dbInitError = err instanceof Error ? `${err.message}${(err as NodeJS.ErrnoException).code ? `（${(err as NodeJS.ErrnoException).code}）` : ""}` : String(err);
  console.error("数据库初始化失败（所有依赖数据库的接口都将不可用）:", err);
}

// Zero-config: apply migrations automatically on startup so a fresh clone or empty DB gets all tables created.
// (Fixes issue #2 "no such table: projects" — data/ is gitignored so a fresh checkout has no tables.)
// Skip during the next build phase: concurrent workers importing this module during the build would all
// try to migrate the same empty DB simultaneously, triggering race conditions ("duplicate column", etc.).
// Migrations only need to run once at runtime (next start / Electron).
if (realDb && process.env.NEXT_PHASE !== "phase-production-build") {
  try {
    if (fs.existsSync(MIGRATIONS_DIR)) {
      migrate(realDb, { migrationsFolder: MIGRATIONS_DIR });
    } else {
      dbMigrationError = `迁移目录不存在: ${MIGRATIONS_DIR}`;
      console.error("Database migration skipped:", dbMigrationError);
    }
  } catch (err) {
    dbMigrationError = err instanceof Error ? err.message : String(err);
    console.error("Database migration failed:", err);
  }

  // Crash-recovery sweep: compose jobs run as in-memory fire-and-forget tasks, so if the
  // process dies mid-render the composition row stays 'composing'/'pending' forever — the web
  // spinner never stops and CLI/MCP pollers hang until their own timeout. On startup, mark
  // rows stuck in a non-terminal status for over 15 minutes as 'failed' so the UI can recover.
  // created_at is stored as unix-epoch SECONDS (drizzle integer { mode: "timestamp" }).
  // Failure here must never break startup (e.g. fresh DB where migration hasn't created the table).
  try {
    const staleCutoff = Math.floor(Date.now() / 1000) - 15 * 60;
    const swept = sqlite!
      .prepare(
        "UPDATE compositions SET status = 'failed' WHERE status IN ('composing', 'pending') AND created_at < ?"
      )
      .run(staleCutoff);
    if (swept.changes > 0) {
      console.warn(`Recovered ${swept.changes} stale composition(s) stuck in composing/pending → marked failed`);
    }
  } catch (err) {
    console.warn("Stale composition sweep failed (non-fatal):", err);
  }
}

/** init 失败时的兜底代理：任何属性访问都抛出带真实原因的异常，由各路由的 try/catch 转成可见的 JSON 错误 */
function makeFailedDbProxy(): ReturnType<typeof drizzle<typeof schema>> {
  return new Proxy({} as ReturnType<typeof drizzle<typeof schema>>, {
    get() {
      throw new Error(`数据库不可用：${dbInitError}。请到 GitHub issue 附上此错误与 /api/health 的截图。`);
    },
  });
}

export const db = realDb ?? makeFailedDbProxy();

// Compatibility wrapper for functional-style callers
export function getDb() {
  return db;
}
